{% set name = "urlchecker" %}
{% set version = "0.0.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cef490371cdb30bf4555c98ddf24dfe58c8f04f156c0e998942abc9ffe7c41c4

build:
  number: 0
  noarch: python
  entry_points:
    - urlchecker=urlchecker.client:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3
    - pytest-runner
  run:
    - python >=3
    - requests

test:
  imports:
    - urlchecker
    - urlchecker.client
    - urlchecker.client.check
    - urlchecker.core
    - urlchecker.core.check
    - urlchecker.core.fileproc
    - urlchecker.core.urlmarker
    - urlchecker.core.urlproc
    - urlchecker.core.exclude
    - urlchecker.main
    - urlchecker.main.github
    - urlchecker.main.utils
    - urlchecker.version
  commands:
    - urlchecker --help


about:
  home: https://github.com/urlstechie/urlchecker-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: tool to collect and validate urls over static files (code and documentation)
  description: |
    urlchecker-python is a python module and command line client to allow for extraction
    and checking of urls in static files, whether they be documentation or code. You can
    also use the library via the urlstechie/urlchecker-action as a GitHub action.
  doc_url: https://urlchecker-python.readthedocs.io/en/latest/
  dev_url: https://github.com/urlstechie/urlchecker-python

extra:
  recipe-maintainers:
    - vsoch
    - SuperKogito
